development:
  dialect: mysql
  datasource: root:root@/neuro?parseTime=true
  dir: migrations
  table: migrations

production:
  dialect: mysql
  datasource: ${DATABASE_URL}
  dir: migrations

develop:
  dialect: mysql
  datasource: core_dev:WwYjehwsrWpHUo6hdzMkDpSLuW7R@unix(/cloudsql/cityxerpa-b57e7:europe-west1:dev-ew1)/core_dev?parseTime=true
  dir: migrations
  table: migrations
