// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	ClockDrawSubtestResults     string
	Evaluations                 string
	ExecutiveFunctionsSubtests  string
	LanguageFluencies           string
	LettersCancellationSubtests string
	Users                       string
	VerbalMemorySubtests        string
}{
	ClockDrawSubtestResults:     "clock_draw_subtest_results",
	Evaluations:                 "evaluations",
	ExecutiveFunctionsSubtests:  "executive_functions_subtests",
	LanguageFluencies:           "language_fluencies",
	LettersCancellationSubtests: "letters_cancellation_subtests",
	Users:                       "users",
	VerbalMemorySubtests:        "verbal_memory_subtests",
}
