name: Run Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    name: Apply DB migrations on Railway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install sql-migrate
        run: go install github.com/rubenv/sql-migrate/...@latest

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.RAILWAY_MYSQL_URL}}
        run: |
          sql-migrate up -env=production
